### PR TITLE
fix build issue on arm64 linux platform

### PR DESCRIPTION
**Pull request by snadampal**
### Description 
Fix build issue on arm64 linux platform

Fixes # - _issue number(s) if exists_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [ x] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [ x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [ x] not needed

### Breaks backward compatibility
- [ ] Yes
- [ x] No
- [ ] Unknown

### Notify the following users
_List users with `@` to send notifications_

### CODE REVIEW

**Comment by isaevil** [comment]
@Vertexwahn could you please take a look?

**Review by Vertexwahn — APPROVED** [review]

**Comment by Vertexwahn** [comment]
@isaevil You cannot modify existing version - you Need to provide a new version, e.g. X.Y.Z.bcr.W

**Review by Vertexwahn — CHANGES_REQUESTED** [review]
See me last commennt

**Comment by isaevil** [comment]
@Vertexwahn you mean updating this file? 
https://github.com/uxlfoundation/oneTBB/blob/master/.bazelversion

**Review by Vertexwahn — APPROVED** [review]

**Comment by Vertexwahn** [comment]
@isaevil Oh sorry there was a missunderstanding on my side ;)

**Review by isaevil — APPROVED** [review]

**Pull request merged**
